```{r}
library(rio)
"csv"='https://github.com/Piero-Llave/TrabajoEstadistica2/raw/master/Violencia%20psicologica%20y%20fisica%20contra%20la%20mujer.csv'

violencia=import(csv)
```

```{r}
library(stringr)

violencia$Pais=str_split(violencia$`Country, ""Age Group"` , ',', simplify=T)[,1]
violencia$Edad= str_split (violencia$`Country, ""Age Group"` , ',', simplify=T)[,2]

```

```{r}
violencia[,c(1)]=NULL
```



```{r}
names(violencia)
violencia$Year=violencia$"\"Year\""
violencia$'Proporcion de violencia psicologica y fisica contra la mujer'=violencia$"\"Proportion of ever-partnered women and girls aged 15-49 years subjected to physical and/or sexual violence by a current or former intimate partner in the previous 12 months\"\""
```

```{r}
violencia[,c(1,2)]=NULL
```

```{r}
violencia$Edad=str_extract_all(violencia$Edad, 
                "\\d+\\-*\\d*")
```

```{r}
violencia$Year=str_extract_all(violencia$Year, 
                "\\d+\\-*\\d*")
```

```{r}
library(readr)
violencia$`Proporcion de violencia psicologica y fisica contra la mujer` = parse_number(violencia$`Proporcion de violencia psicologica y fisica contra la mujer`)
```

```{r}
str(violencia)
```
*Nos quedamos con el rango de edad de 15 a 49 años*
```{r}
violencia=violencia[-c(1:6),]
```

```{r}
violencia=violencia[-c(2),]
```

```{r}
violencia=violencia[-c(2:7,9),]
```

```{r}
violencia=violencia[-c(3:8,10,12:17,19,20:25,27),]
```

```{r}
violencia=violencia[-c(10:14,16,17:22,24,26:31,33,34:39),]
```

```{r}
violencia=violencia[-c(15:18,20:26,28:34,36:42,44:50,52:58),]
```

```{r}
violencia=violencia[-c(21,25:30,32,34:39,41,43:48,50:56),]
#fila 159
```

```{r}
violencia=violencia[-c(30:34,36,38:43,45:50,52,55:60,62:68,70,72:77,79),]
#fila 208
```

```{r}
violencia=violencia[-c(41:46,48:54,56:62,64,66:71,73,76:81,83:89,91:97,99,101:106),]
#fila 275
```

```{r}
violencia=violencia[-c(53:59,61,63:68,70,73:78,80:86,88:94,96,98:102,104,106:110,112:118),]
#fila 342
```

```{r}
violencia=violencia[-c(66:70,72:78,80:86,88:94,96,98:103,105:111,113:119,121,124:129,131:137,139),]
#fila 418
```

```{r}
violencia=violencia[-c(80:85,87,89:93,95,97:102,104:110,112:118,120,126:131,133:139,141:147,149:154),]
#fila 494
```

```{r}
violencia=violencia[-c(96:101,103:106,108,110:115,117:123,125,127:132,134,137:141,143:149,151:157,159),]
#toda la data
```

*Borramos la columna y cambiamos de nombre*
```{r}
violencia[,c(2)]=NULL
```

```{r}
str(violencia)
```

```{r}
names(violencia)=c("Pais", "Año","Violencia contra la mujer 15-49 años")
```

```{r}
violencia$Año=str_split(violencia$Año,'-', simplify = T)[,1]
```

```{r}
violencia$Año=as.numeric(violencia$Año)
```

```{r}
violencia$Pais=trimws(violencia$Pais,whitespace = "[\\h\\v]")
```

```{r}
str(violencia)
```

```{r}
write.csv(violencia,"Violencia contra la mujer 15-49 años.csv", row.names = F)
```

